# Site settings
title: Peter Hoffler
header-img: img/post-bg-05.jpg
email: peterhoffler@gmail.com
description: "Nur ein Blog."
baseurl: "/blog"
url: "http://github.io"
twitter_username: hoffli
github_username:  hoffli
facebook_username:  peterhoffler

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
